"""Agregando fecha_asignacion a Rollo

Revision ID: 6d9a7bab72a7
Revises: 
Create Date: 2025-12-06 21:03:26.025163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9a7bab72a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('linea', sa.String(length=50), nullable=False),
    sa.Column('variedad', sa.String(length=10), nullable=False),
    sa.Column('garantia_anios', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('pais', sa.String(length=3), nullable=True),
    sa.Column('nombre_responsable', sa.String(length=100), nullable=True),
    sa.Column('telefono_personal', sa.String(length=50), nullable=True),
    sa.Column('telefono_negocio', sa.String(length=50), nullable=True),
    sa.Column('direccion_negocio', sa.String(length=200), nullable=True),
    sa.Column('horario_atencion', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rollos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_padre', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_padre')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcodigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_hijo', sa.String(length=60), nullable=False),
    sa.Column('pin_seguridad', sa.String(length=3), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('rollo_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=True),
    sa.Column('cliente_email', sa.String(length=100), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=50), nullable=True),
    sa.Column('cliente_patente', sa.String(length=20), nullable=True),
    sa.Column('fecha_activacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('instalador_correcto', sa.Boolean(), nullable=True),
    sa.Column('review_texto', sa.Text(), nullable=True),
    sa.Column('review_stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rollo_id'], ['rollos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_hijo')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_messages')
    op.drop_table('subcodigos')
    op.drop_table('tickets')
    op.drop_table('rollos')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('productos')
    # ### end Alembic commands ###
